/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.1
  Forc version: 0.68.4
  Fuel-Core version: 0.43.2
*/

import { Contract as __Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  Address,
  BigNumberish,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Enum, Result } from "./common";

export enum ReclaimErrorInput { OnlyOwner = 'OnlyOwner', AlreadyInitialized = 'AlreadyInitialized', HashMismatch = 'HashMismatch', LengthMismatch = 'LengthMismatch', SignatureMismatch = 'SignatureMismatch' };
export enum ReclaimErrorOutput { OnlyOwner = 'OnlyOwner', AlreadyInitialized = 'AlreadyInitialized', HashMismatch = 'HashMismatch', LengthMismatch = 'LengthMismatch', SignatureMismatch = 'SignatureMismatch' };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "[u8; 64]",
      "concreteTypeId": "d78f0e43f153a55a6db5f4b5fd041f036b51911b38f88095a3106eb02fa1eb17",
      "metadataTypeId": 0
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "enum ReclaimError",
      "concreteTypeId": "499605738face3e9bf31bfb7a34b88e86e6bd12a9cc5b246897f86e99b9c496c",
      "metadataTypeId": 1
    },
    {
      "type": "enum std::result::Result<(),enum ReclaimError>",
      "concreteTypeId": "b3362450da45641a650c2bb3c5cf644ab96e01377ab07bb776ee66f6f430ed45",
      "metadataTypeId": 2,
      "typeArguments": [
        "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
        "499605738face3e9bf31bfb7a34b88e86e6bd12a9cc5b246897f86e99b9c496c"
      ]
    }
  ],
  "metadataTypes": [
    {
      "type": "[_; 64]",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "__array_element",
          "typeId": 5
        }
      ]
    },
    {
      "type": "enum ReclaimError",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "OnlyOwner",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AlreadyInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "HashMismatch",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "LengthMismatch",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SignatureMismatch",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::result::Result",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "Ok",
          "typeId": 4
        },
        {
          "name": "Err",
          "typeId": 3
        }
      ],
      "typeParameters": [
        4,
        3
      ]
    },
    {
      "type": "generic E",
      "metadataTypeId": 3
    },
    {
      "type": "generic T",
      "metadataTypeId": 4
    },
    {
      "type": "u8",
      "metadataTypeId": 5
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "new_witness",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ],
      "name": "add_epoch",
      "output": "b3362450da45641a650c2bb3c5cf644ab96e01377ab07bb776ee66f6f430ed45",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "constructor",
      "output": "b3362450da45641a650c2bb3c5cf644ab96e01377ab07bb776ee66f6f430ed45",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "message",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "signature",
          "concreteTypeId": "d78f0e43f153a55a6db5f4b5fd041f036b51911b38f88095a3106eb02fa1eb17"
        }
      ],
      "name": "verify_proof",
      "output": "b3362450da45641a650c2bb3c5cf644ab96e01377ab07bb776ee66f6f430ed45",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "5302431605165188073",
      "concreteTypeId": "499605738face3e9bf31bfb7a34b88e86e6bd12a9cc5b246897f86e99b9c496c"
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [
  {
    "key": "6189f6fb2b7278c2a5f1b1ebfc35d4838d6c414acd1f700a7cf63bfc75e71a2b",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "6189f6fb2b7278c2a5f1b1ebfc35d4838d6c414acd1f700a7cf63bfc75e71a2c",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "85e799f4c3aa6f233223a87cdb1eadf6990c880dd5a269f00eecf4176fabd828",
    "value": "0000000000000040000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cd58e3c38e37f4791aa6e8a708a81e91860bba85f03415bfc19a7f6ddff233fa",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "cd58e3c38e37f4791aa6e8a708a81e91860bba85f03415bfc19a7f6ddff233fb",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class ReclaimContractInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    add_epoch: FunctionFragment;
    constructor: FunctionFragment;
    verify_proof: FunctionFragment;
  };
}

export class ReclaimContract extends __Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: ReclaimContractInterface;
  declare functions: {
    add_epoch: InvokeFunction<[new_witness: string], Result<void, ReclaimErrorOutput>>;
    constructor: InvokeFunction<[], Result<void, ReclaimErrorOutput>>;
    verify_proof: InvokeFunction<[message: string, signature: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]], Result<void, ReclaimErrorOutput>>;
  };

  constructor(
    id: string | Address,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
